apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydre-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hydre-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "hydre-auth.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
